### ISSUE TITLE
Error 400 on SERVER: Expression is not valid as a resource, resource-default, or resource-override

### ISSUE THREAD

**Issue by BeerOpsHQ** [example42/puppet-munin#25]
Hi,

When I add the **server** attribute when calling the munin class, I get the following error on PE2015.3 (puppet 4.3.2)...

e.g.

```
>   class { 'munin':
> # ref https://github.com/example42/puppet-yum/issues/88 - same issue for munin
>     source_dir       => 'puppet:///modules/munin/empty',
>     source_dir_purge => false,
>     server           => '192.168.0.168',      <********
>   }
> 
```

I get the following error message....

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Expression is not valid as a resource, resource-default, or resource-override at /etc/puppetlabs/code/environments/production/modules/munin/manifests/server.pp:40:10 on node monitoring.BLAH.net.au
```

A small syntax update following this ref helped;
- https://groups.google.com/forum/#!topic/puppet-users/9F5Left8LtU

The fix...remove the space on line 40 of manifests/server.pp....

From 
 File_space_['munin.include_dir_server'] {
To 
File['munin.include_dir_server'] {

Hope this helps.

Stephen

**Comment by alvagante** [comment]
Thanks for the notice. Fixed as suggested.

**Comment by stphnwallace** [comment]
You're welcome. I think I read the same issue for your yum module as well.
You might want to take a look.

Stephen

**Comment by alvagante** [comment]
Uhm, I checked and the current yum module manifests validate with Puppet4. If you can point a specific file that would be appreciated, or maybe you tested on an older version.

**Comment by stphnwallace** [comment]
It may have been an older thread I found. Will give you the heads up if i
come across any more :)

Keep up the good work!
